### ISSUE TITLE
Input Label Allow children types

### ISSUE THREAD

**Issue by anshuopinion** [thekaganugur/formik-chakra-ui#136]
![image](https://user-images.githubusercontent.com/50476777/174236649-901d24fd-3059-4af1-8891-54892ffa2c1c.png)

**Comment by thekaganugur** [comment]
I couldn't understand the problem.

```
           <TextareaControl name="notes" 
              label={
              <Flex gap={1}>
                <Box>Locaction</Box> <Box color='tan'>foooooo</Box>
              </Flex>
            }
              />
```

Something like this seems to be working. I see you are using `labelProps`. If you are opting in using label as Node instead of string you `labelProps` won't work.

**Comment by thekaganugur** [comment]
Closing this. Feel free to reopen if the above comment is not enough. Thanks.
@anshuopinion
