### ISSUE TITLE
How do I disable autocomplete?

### ISSUE THREAD

**Issue by kirak64** [thekaganugur/formik-chakra-ui#152]
I need to disable autocomplete but I can't

`<InputControl
                                name="email"
                                label="Email"
                                inputProps={{ type: "email",name:"email", autoComplete:"off" ,placeholder:"user@gmail.com"}} />`

**Comment by thekaganugur** [comment]
Hi,

It seems like working. You are probably referring to Chrome Autofill and there's a  [Stackoverflow Post](https://stackoverflow.com/questions/15738259/disabling-chrome-autofill) about that.

`<input name="firstName" autocomplete="off" id="firstName" class="chakra-input css-1c6j008" value="">` you can see `autocomplete` correctly set to `"off"`.
